#!/usr/bin/env php
<?php
namespace think;

// 命令行入口文件
// 加载基础文件
require __DIR__ . '/vendor/autoload.php';

$pharPath = \Phar::running(false);
if(!defined('IN_PHAR'))
    define('IN_PHAR', $pharPath != "");
// 应用初始化
(new App())->console->run();